<?php
/**
 * includes/phone_countries.php
 * Shared data: country phone codes and country list.
 * Included by customer/register.php and merchant/register.php.
 */

// Phone dial codes — [dial_code, country_name, flag_emoji, iso2]
$PHONE_CODES = [
    ['+234', 'Nigeria',              '🇳🇬', 'NG'],
    ['+233', 'Ghana',                '🇬🇭', 'GH'],
    ['+254', 'Kenya',                '🇰🇪', 'KE'],
    ['+27',  'South Africa',         '🇿🇦', 'ZA'],
    ['+251', 'Ethiopia',             '🇪🇹', 'ET'],
    ['+255', 'Tanzania',             '🇹🇿', 'TZ'],
    ['+256', 'Uganda',               '🇺🇬', 'UG'],
    ['+221', 'Senegal',              '🇸🇳', 'SN'],
    ['+237', 'Cameroon',             '🇨🇲', 'CM'],
    ['+225', 'Côte d\'Ivoire',       '🇨🇮', 'CI'],
    ['+223', 'Mali',                 '🇲🇱', 'ML'],
    ['+226', 'Burkina Faso',         '🇧🇫', 'BF'],
    ['+227', 'Niger',                '🇳🇪', 'NE'],
    ['+250', 'Rwanda',               '🇷🇼', 'RW'],
    ['+260', 'Zambia',               '🇿🇲', 'ZM'],
    ['+263', 'Zimbabwe',             '🇿🇼', 'ZW'],
    ['+258', 'Mozambique',           '🇲🇿', 'MZ'],
    ['+244', 'Angola',               '🇦🇴', 'AO'],
    ['+229', 'Benin',                '🇧🇯', 'BJ'],
    ['+228', 'Togo',                 '🇹🇬', 'TG'],
    ['+232', 'Sierra Leone',         '🇸🇱', 'SL'],
    ['+231', 'Liberia',              '🇱🇷', 'LR'],
    ['+220', 'Gambia',               '🇬🇲', 'GM'],
    ['+224', 'Guinea',               '🇬🇳', 'GN'],
    ['+243', 'DR Congo',             '🇨🇩', 'CD'],
    ['+212', 'Morocco',              '🇲🇦', 'MA'],
    ['+20',  'Egypt',                '🇪🇬', 'EG'],
    ['+216', 'Tunisia',              '🇹🇳', 'TN'],
    ['+213', 'Algeria',              '🇩🇿', 'DZ'],
    ['+218', 'Libya',                '🇱🇾', 'LY'],
    ['+249', 'Sudan',                '🇸🇩', 'SD'],
    ['+252', 'Somalia',              '🇸🇴', 'SO'],
    ['+265', 'Malawi',               '🇲🇼', 'MW'],
    ['+267', 'Botswana',             '🇧🇼', 'BW'],
    ['+264', 'Namibia',              '🇳🇦', 'NA'],
    ['+268', 'Eswatini',             '🇸🇿', 'SZ'],
    ['+266', 'Lesotho',              '🇱🇸', 'LS'],
    ['+248', 'Seychelles',           '🇸🇨', 'SC'],
    ['+230', 'Mauritius',            '🇲🇺', 'MU'],
    ['+44',  'United Kingdom',       '🇬🇧', 'GB'],
    ['+1',   'United States',        '🇺🇸', 'US'],
    ['+1',   'Canada',               '🇨🇦', 'CA'],
    ['+33',  'France',               '🇫🇷', 'FR'],
    ['+49',  'Germany',              '🇩🇪', 'DE'],
    ['+31',  'Netherlands',          '🇳🇱', 'NL'],
    ['+39',  'Italy',                '🇮🇹', 'IT'],
    ['+34',  'Spain',                '🇪🇸', 'ES'],
    ['+32',  'Belgium',              '🇧🇪', 'BE'],
    ['+46',  'Sweden',               '🇸🇪', 'SE'],
    ['+47',  'Norway',               '🇳🇴', 'NO'],
    ['+45',  'Denmark',              '🇩🇰', 'DK'],
    ['+41',  'Switzerland',          '🇨🇭', 'CH'],
    ['+971', 'UAE',                  '🇦🇪', 'AE'],
    ['+966', 'Saudi Arabia',         '🇸🇦', 'SA'],
    ['+91',  'India',                '🇮🇳', 'IN'],
    ['+86',  'China',                '🇨🇳', 'CN'],
    ['+81',  'Japan',                '🇯🇵', 'JP'],
    ['+82',  'South Korea',          '🇰🇷', 'KR'],
    ['+61',  'Australia',            '🇦🇺', 'AU'],
    ['+64',  'New Zealand',          '🇳🇿', 'NZ'],
    ['+55',  'Brazil',               '🇧🇷', 'BR'],
];

// Full country list for country select dropdowns
$COUNTRIES = [
    'Nigeria', 'Ghana', 'Kenya', 'South Africa', 'Ethiopia', 'Tanzania',
    'Uganda', 'Senegal', 'Cameroon', 'Côte d\'Ivoire', 'Mali', 'Burkina Faso',
    'Niger', 'Rwanda', 'Zambia', 'Zimbabwe', 'Mozambique', 'Angola', 'Benin',
    'Togo', 'Sierra Leone', 'Liberia', 'Gambia', 'Guinea',
    'Democratic Republic of Congo', 'Morocco', 'Egypt', 'Tunisia', 'Algeria',
    'Libya', 'Sudan', 'Somalia', 'Malawi', 'Botswana', 'Namibia', 'Eswatini',
    'Lesotho', 'Seychelles', 'Mauritius', 'Cape Verde', 'Djibouti', 'Eritrea',
    'Equatorial Guinea', 'Gabon', 'Republic of Congo', 'Central African Republic',
    'Chad', 'Comoros', 'Madagascar', 'São Tomé and Príncipe',
    'United Kingdom', 'United States', 'Canada', 'France', 'Germany',
    'Netherlands', 'Italy', 'Spain', 'Belgium', 'Sweden', 'Norway', 'Denmark',
    'Switzerland', 'Portugal', 'Ireland', 'Finland', 'Austria', 'Poland',
    'UAE', 'Saudi Arabia', 'India', 'China', 'Japan', 'South Korea',
    'Australia', 'New Zealand', 'Brazil', 'Other',
];
